name: attendance
version: 1.0.0+1
publish_to: none
description: A software for Remark HB that helps employee attendance.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  location: ^4.4.0
  geocoding: ^2.0.5
  cached_network_image: ^3.2.3
  zoom_tap_animation: ^1.1.0
  font_awesome_flutter: ^10.3.0
  # intl: ^0.18.0
  date_time_picker: ^2.1.0
  platform_device_id: ^1.0.1
  expandable: ^5.0.1
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^13.0.0
  flutter_spinkit: ^5.1.0
  internet_connection_checker: ^1.0.0+1
  ntp: ^2.0.0
  flutter_downloader: ^1.10.2
  install_plugin_v2: ^1.0.0
  downloads_path_provider_28: ^0.1.2
  permission_handler: ^10.2.0
  weather_icons: ^3.0.0
  simple_gradient_text: ^1.2.4
  intl: ^0.17.0
  proste_bezier_curve: ^2.0.2

  get: 4.6.5
  flutter: 
    sdk: flutter
  package_info_plus: ^3.0.3
  dio: ^5.0.0
  get_storage: ^2.0.3

dev_dependencies: 
  # flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/logo/
    - assets/images/

  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/remark.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/remark.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/remark.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/remark.png"